// src/services/RealTimeRiskEngine.ts
import Redis from "ioredis";
import { positionRegistry } from "./PositionRegistry";
import { redisBullConnection } from "../utils/redis";
import { SignalBroadcastService } from "./SignalBroadcastService";
import { SignalService } from "./SignalService";
import log from "../utils/logger";

export interface RiskMetrics {
  evaluationsCount: number;
  evaluationsPerSec: number;
  avgEvaluationLatencyUs: number; // Latency in Microseconds
  triggerCount: number;
  duplicateTriggerRejects: number;
  cooldownSuppressions: number;
  tickToExitLatencyMs: number;
}

export class RealTimeRiskEngine {
  private static instance: RealTimeRiskEngine;
  private subRedis: Redis | null = null;
  private lockRedis: Redis;
  private isRunning = false;
  private startupCorrelationId: string = "unknown";

  public setStartupCorrelationId(id: string) {
    this.startupCorrelationId = id;
    log.info(`[RiskEngine] Configured Startup Correlation ID: ${id}`);
  }

  // Real-time telemetry metrics
  private metrics: RiskMetrics = {
    evaluationsCount: 0,
    evaluationsPerSec: 0,
    avgEvaluationLatencyUs: 0,
    triggerCount: 0,
    duplicateTriggerRejects: 0,
    cooldownSuppressions: 0,
    tickToExitLatencyMs: 0,
  };

  private evalCounterThisSec = 0;
  private throughputTimer: NodeJS.Timeout | null = null;

  private constructor() {
    this.lockRedis = new Redis(redisBullConnection as any);
    this.lockRedis.on("error", (err) => log.error("[RiskEngine] Lock Redis Error:", err));

    // Calculate throughput throughput per second
    this.throughputTimer = setInterval(() => {
      this.metrics.evaluationsPerSec = this.evalCounterThisSec;
      this.tickCounterReset();
    }, 1000);
  }

  public static getInstance(): RealTimeRiskEngine {
    if (!RealTimeRiskEngine.instance) {
      RealTimeRiskEngine.instance = new RealTimeRiskEngine();
    }
    return RealTimeRiskEngine.instance;
  }

  private tickCounterReset() {
    this.evalCounterThisSec = 0;
  }

  getMetrics(): RiskMetrics {
    return { ...this.metrics };
  }

  /**
   * Spawns a dedicated Redis Pub/Sub client that isolates the risk evaluations
   * completely from UI streams or API routes to prevent event-loop starvation.
   */
  start() {
    if (this.isRunning) return;
    this.isRunning = true;

    log.info("[RiskEngine] Initializing Dedicated Real-Time Risk Monitor Pipeline...");
    
    this.subRedis = new Redis(redisBullConnection as any);
    this.subRedis.on("error", (err) => log.error("[RiskEngine] Sub Redis Error:", err));

    // Subscribe to all volatile ticks generated by the TickEngineService
    this.subRedis.psubscribe("ticks:*");
    
    this.subRedis.on("pmessage", (pattern, channel, message) => {
      this.handleIncomingTickSafe(message);
    });
  }

  stop() {
    if (!this.isRunning) return;
    this.isRunning = false;
    
    if (this.subRedis) {
      this.subRedis.disconnect();
      this.subRedis = null;
    }
    if (this.throughputTimer) {
      clearInterval(this.throughputTimer);
      this.throughputTimer = null;
    }
    log.warn("[RiskEngine] Risk monitor pipeline halted.");
  }

  // 🛡️ HOT TICK PATH: MUST NEVER BLOCK, QUERY DB, OR ACCESSS FILES
  private async handleIncomingTickSafe(message: string) {
    const hrStart = process.hrtime();
    this.metrics.evaluationsCount += 1;
    this.evalCounterThisSec += 1;

    try {
      const parsed = JSON.parse(message);
      const { exchange, token, ltp, timestamp } = parsed;

      if (!exchange || !token || !ltp) return;

      // Scale tick price to Paisa (Integer Math) to eliminate floating-point drift
      const ltpPaisa = Math.round(ltp * 100);

      // O(1) Fast resolution of active registered positions
      const activePositions = positionRegistry.getPositionsByToken(exchange, token);
      if (activePositions.length === 0) return;

      for (const pos of activePositions) {
        // 1. Strict Position State Validations
        if (pos.status !== "OPEN" && pos.status !== "PARTIALLY_EXITED") {
          continue;
        }

        if (pos.remainingQty <= 0) {
          continue;
        }

        // 2. Evaluate SL / TP Limits using exact Integer Paisa Arithmetic
        const isBuy = pos.side === "BUY";
        
        const slHit = isBuy ? ltpPaisa <= pos.stopLossPaisa : ltpPaisa >= pos.stopLossPaisa;
        const targetHit = isBuy ? ltpPaisa >= pos.targetPaisa : ltpPaisa <= pos.targetPaisa;

        if (slHit || targetHit) {
          const reason = slHit ? "STOP_LOSS" : "TAKE_PROFIT";
          
          // 3. Atomically Lock & Evaluate Trigger using Redis SETNX to guarantee Exactly-Once execution
          const lockKey = `risk:triggered:${pos.positionId}`;
          const locked = await this.lockRedis.set(lockKey, "1", "EX", 60, "NX"); // 60s cooldown limit

          if (!locked) {
            this.metrics.duplicateTriggerRejects += 1;
            continue; // Trigger is already in-flight or closed, skip processing
          }

          // 4. Update memory state registry to EXITING immediately to block concurrent tick checks
          positionRegistry.updateState(pos.positionId, "RISK_TRIGGERED");
          positionRegistry.updateState(pos.positionId, "EXITING");
          
          this.metrics.triggerCount += 1;

          const tickToTriggerTime = Date.now() - timestamp;
          this.metrics.tickToExitLatencyMs = tickToTriggerTime;

          log.warn(`[RiskEngine] RISK BREACH! posId: ${pos.positionId}, token: ${token}, LTP Paisa: ${ltpPaisa}, SL Paisa: ${pos.stopLossPaisa}, Target Paisa: ${pos.targetPaisa}, Breach Type: ${reason}. Trigger Latency: ${tickToTriggerTime}ms`);

          // 5. Asynchronously dispatch the flattening exit order to OMS / execution workers without blocking
          this.dispatchExitSignalAsync(pos, ltp, reason);
        }
      }
    } catch (err: any) {
      log.error("[RiskEngine] Exception in hot path:", err.message);
    } finally {
      const hrDiff = process.hrtime(hrStart);
      // Latency in microseconds: seconds * 1e6 + nanoseconds / 1000
      const latencyUs = Math.round(hrDiff[0] * 1e6 + hrDiff[1] / 1000);
      
      // Rolling average evaluation latency calculation
      this.metrics.avgEvaluationLatencyUs = Math.round(
        (this.metrics.avgEvaluationLatencyUs * 19 + latencyUs) / 20
      );
    }
  }

  private async dispatchExitSignalAsync(pos: any, triggerPrice: number, reason: string) {
    try {
      // Build exit signal contract payload and pipe to transactional SignalService
      const mockExitSignal = {
        symbol: pos.tradingsymbol,
        exchange: pos.exchange,
        side: pos.side === "BUY" ? "SELL" as const : "BUY" as const, // Close position by reversing side
        tradingsymbol: pos.tradingsymbol,
        symboltoken: pos.symboltoken,
        price: triggerPrice,
        quantity: pos.remainingQty,
        strategy: `${pos.runId}_RISK_${reason}`,
        signalType: "EXIT" as const,
        executionMode: "SERVER" as const,
      };

      log.info(`[RiskEngine] Creating risk exit signal. Position: ${pos.positionId}, Reversal Side: ${mockExitSignal.side}, Qty: ${mockExitSignal.quantity}`);
      
      const createdSignal = await SignalService.createSignal(mockExitSignal);
      if (createdSignal?._id) {
        log.info(`[RiskEngine] Dispatched asynchronous exit signal for position ${pos.positionId}. Signal ID: ${createdSignal._id}`);
        await SignalBroadcastService.broadcast(String(createdSignal._id));
      }
    } catch (err: any) {
      log.error(`[RiskEngine] Failed to dispatch exit signal for position ${pos.positionId}:`, err.message);
    }
  }
}

export const realTimeRiskEngine = RealTimeRiskEngine.getInstance();
